### ISSUE TITLE
Auto toggle on blur background when joining in Google Meet

### ISSUE THREAD

**Issue by anshulahuja98** [devlup-labs/meet-scheduler#80] opened 2020-10-21 09:27 UTC

**Comment by DarshitJain04** [comment] 2020-10-24 09:19
@anshulahuja98 I think by default the blur background option is on

**Comment by anshulahuja98** [comment] 2020-10-25 14:34
@DarshitJain04 it isn't

**Comment by DarshitJain04** [comment] 2020-10-26 02:56
> @DarshitJain04 it isn't

Oh is it? Because whenever a link opens for me, the blur background is on by default

**Comment by krushil1** [comment] 2020-11-16 05:06
@DarshitJain04 Does the blurred background issue still persist?

**Comment by DarshitJain04** [comment] 2020-11-16 05:32
> @DarshitJain04 Does the blurred background issue still persist?

Yes, the issue is still open. But as I mentioned earlier, whenever I open any meeting, the blur option is already on for me, which is not the case with Anshul. So I'm not sure if this is some issue with Google Meet itself.

**Comment by anshulahuja98** [comment] 2020-11-16 07:04
@DarshitJain04 can you try the same in another browser or incognito window?

**Comment by krushil1** [comment] 2020-11-16 16:21
@DarshitJain04 Did you try clearing the cookies and the cache in the browser that you are using?

**Comment by DarshitJain04** [comment] 2020-11-17 05:19
> @DarshitJain04 Did you try clearing the cookies and the cache in the browser that you are using?

I confirmed it with some more people. They said that if we select the blur background option once, the same setting persists for other links also.
So I think it's a one time issue. There's no need to add another few lines of code for this. So I'm closing this issue. 
Anyways, thanks for showing interest to work on this issue✌️

**Closed** 2020-11-17 05:20 UTC
